"""New Tables

Revision ID: ba6edea69b5b
Revises: 
Create Date: 2023-07-19 03:34:45.789296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6edea69b5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_node', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post', sa.Integer(), nullable=False))
        batch_op.alter_column('author',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['parent_node'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['author'], ['username'])
        batch_op.create_foreign_key(None, 'posts', ['post'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['id'])
        batch_op.alter_column('author',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('post')
        batch_op.drop_column('parent_node')

    # ### end Alembic commands ###
